#!/bin/sh

case "$1" in
    purge|remove)
    	rm -rf /usr/share/texmf/fonts/type1/public/cm-super/
	mktexlsr
	update-updmap
	# if the -sys variant exists (texlive, tetex3) call it, 
	# otherwise call the original updmap
	if which updmap-sys >/dev/null 2>&1 ; then
	    updmap-sys
	else
	    updmap
	fi
	;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

#DEBHELPER#
